import { useQuery } from "@tanstack/react-query";
import { Link } from "wouter";
import { Phone } from "lucide-react";
import { TextHighlighter } from "@/components/ui/text-highlighter";

import mangoLoverLogo from "@assets/mango-lover-logo.avif";
import { WhatsAppBrandIcon } from "@/features/kalojira-mixed/campaign-layout";
import { KALOJIRA_CAMPAIGN_PHONE_HREF, KALOJIRA_CAMPAIGN_WHATSAPP_HREF } from "@/features/kalojira-mixed/content";
import { KalojiraCheckout } from "@/features/kalojira-mixed/kalojira-checkout";
import { resolveKalojiraCheckoutStatus } from "@/features/kalojira-mixed/checkout-state";
import { getKalojiraPackOptions } from "@/features/kalojira-mixed/order";
import { fetchStorefrontProduct, fetchStorefrontProductInventory, mergeInventory } from "@/lib/storefront-products";

export default function KatimonMangoPage() {
  const slug = "katimon-mango";
  const productQuery = useQuery({ queryKey: ["merchant-suite-product", slug], queryFn: () => fetchStorefrontProduct(slug), refetchInterval: 8000 });
  const inventoryQuery = useQuery({ queryKey: ["merchant-suite-inventory", slug], queryFn: () => fetchStorefrontProductInventory(slug), refetchInterval: 8000 });
  const product = mergeInventory(productQuery.data, inventoryQuery.data?.inventory);
  const status = resolveKalojiraCheckoutStatus({ hasProduct: Boolean(product), hasOrderablePacks: product ? getKalojiraPackOptions(product).length > 0 : false, productIsPending: productQuery.isPending, productIsError: productQuery.isError, inventoryIsError: inventoryQuery.isError, inventoryIsFetched: inventoryQuery.isFetched, hasInventory: Boolean(inventoryQuery.data?.inventory) });

  if (productQuery.isPending) return <div className="flex min-h-screen items-center justify-center bg-white" aria-busy="true"><span className="sr-only">পণ্য লোড হচ্ছে…</span><span aria-hidden="true" className="size-8 animate-pulse rounded-full bg-[#eab308]/50" /></div>;
  if (!product) return <div className="flex min-h-screen flex-col items-center justify-center gap-4 bg-white px-6 text-center"><h1 className="text-2xl font-bold">পণ্যটি পাওয়া যায়নি</h1><Link href="/products" className="rounded-full bg-black px-5 py-3 text-sm text-white">সব পণ্য দেখুন</Link></div>;

  return <div className="min-h-screen bg-white text-[#19382d]">
    <header className="sticky top-0 z-40 border-b border-black/10 bg-white/95 backdrop-blur"><div className="relative mx-auto flex h-[68px] max-w-6xl items-center justify-between px-4 sm:h-[76px] sm:px-6"><Link href="/step/katimon-mango" aria-label="ম্যাংগো লাভার কাটিমন আম পেজ" className="absolute left-1/2 flex -translate-x-1/2 items-center"><img src={mangoLoverLogo} alt="ম্যাংগো লাভার" className="h-8 w-auto sm:h-9" decoding="async" /></Link><a href={KALOJIRA_CAMPAIGN_PHONE_HREF} aria-label="ফোনে অর্ডার করুন" className="inline-flex min-h-11 min-w-11 items-center justify-center gap-2 rounded-[4px] border border-black/15 bg-white px-3 text-[10px] font-bold uppercase tracking-[0.16em] text-black transition-colors hover:bg-black hover:text-white"><Phone className="size-4" strokeWidth={2} aria-hidden="true" /><span className="hidden sm:inline">কল করুন</span></a><nav aria-label="যোগাযোগ" className="ml-auto flex items-center"><a href={KALOJIRA_CAMPAIGN_WHATSAPP_HREF} aria-label="WhatsApp-এ অর্ডার করুন" target="_blank" rel="noopener noreferrer" className="inline-flex min-h-11 min-w-11 items-center justify-center gap-2 rounded-[4px] border border-[#25d366]/50 bg-[#f4fff7] px-3 text-[10px] font-bold uppercase tracking-[0.16em] text-[#168a45] transition-colors hover:bg-[#25d366] hover:text-white"><WhatsAppBrandIcon className="size-4" /><span className="hidden sm:inline">WhatsApp</span></a></nav></div></header>
    <main>
      <section className="mx-auto grid max-w-6xl gap-8 px-0 pb-16 pt-0 md:grid-cols-2 md:items-center md:px-5 md:pt-16">
        <div className="order-2 px-5 md:order-1 md:px-0"><p className="text-sm font-bold tracking-[0.2em] text-[#b98500]">অফসিজনের প্রিমিয়াম আম</p><h1 className="mt-4 text-4xl font-extrabold leading-tight md:text-6xl">বাগান থেকে সরাসরি<br /><span className="text-[#b98500]">কাটিমন আম</span></h1><p className="mt-5 max-w-xl text-lg leading-8 text-[#19382d]/70">প্রাকৃতিকভাবে ধীরে ধীরে পাকা, সুগন্ধি ও মিষ্টি কাটিমন আম—বিশুদ্ধ স্বাদে আপনার ঘরে।</p><a href="#order" className="mt-8 inline-flex rounded-full bg-[#eab308] px-7 py-4 font-extrabold text-[#19382d]">এখনই অর্ডার করুন</a></div>
        <div className="order-1 overflow-hidden rounded-none bg-[#f2df9a] shadow-sm md:order-2 md:rounded-3xl"><img src="/katimon-mango-hero.webp" alt="কাটিমন আমের বাগানে তাজা আম" className="h-auto w-full object-contain" /></div>
      </section>
      <section aria-labelledby="katimon-packages" className="mx-auto max-w-6xl px-5 pb-16">
        <div className="mb-7 text-center"><p className="text-[10px] font-bold uppercase tracking-[0.28em] text-[#b98500]">বিশেষ প্যাকেজ</p><h2 id="katimon-packages" className="mt-3 text-2xl font-bold text-[#19382d] md:text-3xl">আপনার পছন্দের প্যাক বেছে নিন</h2></div>
        <div className="grid gap-4 md:grid-cols-2">
          <article className="relative flex min-h-[360px] flex-col rounded-[4px] border border-black/15 bg-white p-6 md:p-8"><div className="pr-[44%]"><img src="/katimon-mango-6kg.webp" alt="৬ কেজি কাটিমন আমের প্যাকেজ" className="absolute right-1 top-3 h-64 w-[55%] object-contain md:right-6 md:top-8 md:h-64 md:w-[50%]" /><p className="text-[10px] font-bold uppercase tracking-[0.28em] text-black/45">কাটিমন আম</p><h3 className="mt-3 text-3xl font-bold text-[#19382d]">6KG</h3><p className="mt-2 text-2xl font-light text-[#b98500]">৳1,080</p><ul className="mt-6 space-y-2 text-sm leading-6 text-[#19382d]"><li className="flex items-center gap-3 py-1 font-medium"><span className="relative flex size-9 shrink-0 rotate-[-6deg] items-center justify-center rounded-[47%_53%_51%_49%] border-2 border-[#b98500] text-sm font-bold text-[#b98500] after:absolute after:inset-[-3px] after:rotate-[13deg] after:rounded-[53%_47%_49%_51%] after:border after:border-[#b98500]/60 after:content-['']" aria-hidden="true">১</span><span>বেশি পরিমাণে, বেশি সাশ্রয়ী</span></li><li className="flex items-center gap-3 py-1 font-medium"><span className="relative flex size-9 shrink-0 rotate-[-6deg] items-center justify-center rounded-[47%_53%_51%_49%] border-2 border-[#b98500] text-sm font-bold text-[#b98500] after:absolute after:inset-[-3px] after:rotate-[13deg] after:rounded-[53%_47%_49%_51%] after:border after:border-[#b98500]/60 after:content-['']" aria-hidden="true">২</span><span>পরিবার ও অতিথি আপ্যায়নে আদর্শ</span></li><li className="flex items-center gap-3 py-1 font-medium"><span className="relative flex size-9 shrink-0 rotate-[-6deg] items-center justify-center rounded-[47%_53%_51%_49%] border-2 border-[#b98500] text-sm font-bold text-[#b98500] after:absolute after:inset-[-3px] after:rotate-[13deg] after:rounded-[53%_47%_49%_51%] after:border after:border-[#b98500]/60 after:content-['']" aria-hidden="true">৩</span><span>সুমিষ্ট ও সুগন্ধি স্বাদ</span></li><li className="flex items-center gap-3 py-1 font-medium"><span className="relative flex size-9 shrink-0 rotate-[-6deg] items-center justify-center rounded-[47%_53%_51%_49%] border-2 border-[#b98500] text-sm font-bold text-[#b98500] after:absolute after:inset-[-3px] after:rotate-[13deg] after:rounded-[53%_47%_49%_51%] after:border after:border-[#b98500]/60 after:content-['']" aria-hidden="true">৪</span><span className="whitespace-nowrap text-sm">ছোট পরিবারের জন্য উপযুক্ত</span></li></ul></div><div className="mt-auto pt-8"><a href="#order" className="inline-flex w-full items-center justify-center rounded-[4px] bg-[#eab308] px-5 py-3 text-sm font-bold text-[#19382d] transition-colors hover:bg-[#d59f00]">অর্ডার করুন</a></div></article>
          <article className="relative flex min-h-[360px] flex-col rounded-[4px] border border-[#b98500]/45 bg-white p-6 md:p-8"><div className="pr-[44%]"><img src="/katimon-mango-10kg.webp" alt="১০ কেজি কাটিমন আমের প্যাকেজ" className="absolute right-1 top-3 h-64 w-[55%] object-contain md:right-6 md:top-8 md:h-64 md:w-[50%]" /><p className="text-[10px] font-bold uppercase tracking-[0.28em] text-black/45">কাটিমন আম</p><h3 className="mt-3 text-3xl font-bold text-[#19382d]">10KG</h3><p className="mt-2 text-2xl font-light text-[#b98500]">৳1,800</p><ul className="mt-6 space-y-2 text-sm leading-6 text-[#19382d]"><li className="flex items-center gap-3 py-1 font-medium"><span className="relative flex size-9 shrink-0 rotate-[-6deg] items-center justify-center rounded-[47%_53%_51%_49%] border-2 border-[#b98500] text-sm font-bold text-[#b98500] after:absolute after:inset-[-3px] after:rotate-[13deg] after:rounded-[53%_47%_49%_51%] after:border after:border-[#b98500]/60 after:content-['']" aria-hidden="true">১</span><span>বাগান থেকে সরাসরি সংগ্রহ</span></li><li className="flex items-center gap-3 py-1 font-medium"><span className="relative flex size-9 shrink-0 rotate-[-6deg] items-center justify-center rounded-[47%_53%_51%_49%] border-2 border-[#b98500] text-sm font-bold text-[#b98500] after:absolute after:inset-[-3px] after:rotate-[13deg] after:rounded-[53%_47%_49%_51%] after:border after:border-[#b98500]/60 after:content-['']" aria-hidden="true">২</span><span>প্রাকৃতিকভাবে পাকানো</span></li><li className="flex items-center gap-3 py-1 font-medium"><span className="relative flex size-9 shrink-0 rotate-[-6deg] items-center justify-center rounded-[47%_53%_51%_49%] border-2 border-[#b98500] text-sm font-bold text-[#b98500] after:absolute after:inset-[-3px] after:rotate-[13deg] after:rounded-[53%_47%_49%_51%] after:border after:border-[#b98500]/60 after:content-['']" aria-hidden="true">৩</span><span>সুমিষ্ট ও সুগন্ধি স্বাদ</span></li><li className="flex items-center gap-3 py-1 font-medium"><span className="relative flex size-9 shrink-0 rotate-[-6deg] items-center justify-center rounded-[47%_53%_51%_49%] border-2 border-[#b98500] text-sm font-bold text-[#b98500] after:absolute after:inset-[-3px] after:rotate-[13deg] after:rounded-[53%_47%_49%_51%] after:border after:border-[#b98500]/60 after:content-['']" aria-hidden="true">৪</span><span className="whitespace-nowrap text-sm">ভাগ করে উপভোগের জন্য উপযুক্ত</span></li></ul></div><div className="mt-auto pt-8"><a href="#order" className="inline-flex w-full items-center justify-center rounded-[4px] bg-[#eab308] px-5 py-3 text-sm font-bold text-[#19382d] transition-colors hover:bg-[#d59f00]">অর্ডার করুন</a></div></article>
        </div>
      </section>
      <section className="mx-auto max-w-4xl px-5 pb-8 text-center"><div className="mx-auto max-w-3xl text-lg leading-[1.85] text-[#19382d]/75 md:text-xl"><p><TextHighlighter>মৌসুমের অপেক্ষা নয়</TextHighlighter>—কাটিমনের স্বাদ সারা বছর। বাগান থেকে সরাসরি সংগ্রহ করা <TextHighlighter>পরিপক্ক কাটিমন আম</TextHighlighter> ধীরে ধীরে পেকে তৈরি করে <TextHighlighter>সুমিষ্ট স্বাদ</TextHighlighter>, <TextHighlighter>মনভোলানো সুগন্ধ</TextHighlighter> ও নরম শাঁসের অনন্য অভিজ্ঞতা। প্রতিটি আমে থাকে <TextHighlighter>বাগানের সতেজতা</TextHighlighter>, স্বাভাবিক রং আর কাটিমনের নিজস্ব স্বাদের বৈশিষ্ট্য।</p></div><img src="/katimon-mango-ripening.webp" alt="কাঁচা থেকে পাকা কাটিমন আমের ধাপ" className="mx-auto mt-4 h-auto w-full object-contain" /><div className="mt-8 grid gap-3 text-left sm:grid-cols-3"><div className="rounded-2xl bg-white/70 p-5"><strong className="block text-lg">অথেনটিক আম</strong><span className="text-sm text-black/55">বাগান থেকে সরাসরি সংগ্রহ</span></div><div className="rounded-2xl bg-white/70 p-5"><strong className="block text-lg">কেমিক্যালমুক্ত</strong><span className="text-sm text-black/55">প্রাকৃতিক স্বাদ ও ঘ্রাণ</span></div><div className="rounded-2xl bg-white/70 p-5"><strong className="block text-lg">ক্যাশ অন ডেলিভারি</strong><span className="text-sm text-black/55">হাতে পেয়ে মূল্য পরিশোধ</span></div></div><img src="/katimon-mango-benefits.webp" alt="কাটিমন আমের বৈশিষ্ট্য ও উপকারিতা" className="-mx-5 mt-8 h-auto w-[calc(100%+2.5rem)] max-w-none object-contain md:-mx-16 md:mt-10 md:w-[calc(100%+8rem)]" /></section>
      <section id="order" className="mx-auto max-w-4xl scroll-mt-24 px-5 pb-20"><KalojiraCheckout product={product} status={status} productQuery={productQuery} inventoryQuery={inventoryQuery} deliveryCharge={100} onRetry={() => void Promise.all([productQuery.refetch(), inventoryQuery.refetch()])} /></section>
    </main>
    <footer className="border-t border-black/15 bg-white text-[#19382d]"><div className="mx-auto max-w-6xl px-4 py-6 md:px-5 md:py-16"><div className="grid gap-5 border-b border-black/15 pb-5 md:gap-10 md:pb-10 md:grid-cols-[1.2fr_0.8fr_1fr] md:gap-16"><div><img src={mangoLoverLogo} alt="ম্যাংগো লাভার" className="h-9 w-auto" /><p className="mt-3 max-w-xs md:mt-5 text-sm leading-7 text-black/55">প্রকৃতির স্বাদ, যত্নের সঙ্গে পৌঁছে দিই আপনার ঘরে।</p></div><div><p className="text-[10px] font-bold uppercase tracking-[0.25em] text-black/45">যোগাযোগ</p><div className="mt-3 flex flex-row gap-2 md:mt-4 md:gap-3"><a href={KALOJIRA_CAMPAIGN_PHONE_HREF} className="inline-flex min-h-10 w-full max-w-xs items-center gap-3 rounded-[4px] border border-black/15 bg-white px-3 py-2 text-sm underline underline-offset-4 transition-colors hover:bg-black hover:text-white "><Phone className="size-4" />কল করুন</a><a href={KALOJIRA_CAMPAIGN_WHATSAPP_HREF} target="_blank" rel="noopener noreferrer" className="inline-flex min-h-10 w-full max-w-xs items-center gap-3 rounded-[4px] border border-[#25d366]/50 bg-[#f4fff7] px-3 py-2 text-sm text-[#168a45] transition-colors hover:bg-[#25d366] hover:text-white "><WhatsAppBrandIcon className="size-4" />হোয়াটসঅ্যাপ করুন</a></div></div><div><p className="text-[10px] font-bold uppercase tracking-[0.25em] text-black/45">ম্যাংগো লাভার - Mango Lover</p><p className="mt-3 text-sm leading-6 md:mt-4 md:leading-7 text-black/55">পুষ্টিবিদ মুরাদ পারভেজ পরিচালিত "ম্যাংগো লাভার" একটি ই-কমার্স প্ল্যাটফর্ম যার প্রধান লক্ষ্য প্রতিটি ঘরে ভেজালমুক্ত ও খাঁটি নিরাপদ খাবার পৌঁছে দেয়া।</p></div></div><div className="flex flex-col gap-5 pt-5 text-[10px] md:pt-7 font-bold uppercase tracking-[0.16em] text-black/45 md:flex-row md:items-center md:justify-between"><p>© ২০২৬ ম্যাংগো লাভার · <a href="https://www.bing.com/maps/default.aspx?v=2&pc=FACEBK&mid=8100&where1=Nowhata%2C%20Paba%2C%20Rajshahi%2C%20Bangladesh%2C%206213&FORM=FBKPL1&mkt=en-GB&fbclid=IwcGRvZgVleHRuA2FlbQIxMABicmlkETF6NkRrSDdLYnpNWTdxV1BXc3J0YwZhcHBfaWQQMjIyMDM5MTc4ODIwMDg5MgABHmAiKlidxKiGWX-ICOpph9o7luUYwBIhtkKdEl3gDFwJb8QY-0os8NFSknan_aem_SGLjUOid6OtmixDnZESu1g" target="_blank" rel="noopener noreferrer" className="underline underline-offset-4 hover:text-black">নওহাটা, পবা, রাজশাহী, বাংলাদেশ, ৬২১৩</a></p><nav aria-label="নীতিমালা" className="flex flex-wrap gap-x-5 gap-y-2"><Link href="/privacy-policy" className="hover:text-black">Privacy Policy</Link><Link href="/refund-and-return-policy" className="hover:text-black">Refund & Return</Link><Link href="/terms-and-conditions" className="hover:text-black">Terms</Link></nav></div></div><div className="h-1 bg-[#eab308]" /></footer>
  </div>;
}
